version: "3.7"

services:
  app:
    build: .
    restart: always
    ports:
      - 29000:29000
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - static-data:/static
      - moodle-local-db:/etc/data

  server:
    build: ./server
    restart: always
    volumes:
      - static-data:/static
    ports:
      - 443:443
      - 80:80
    depends_on:
      - app

volumes:
  static-data:
  moodle-local-db: